global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/(( API ))'

route:
  receiver: 'default'
  group_by: ['instance']
  group_wait: 1s
  group_interval: 3s
  repeat_interval: 1h
  
  routes:
  - match:
      env: devops
    receiver: 'devops-alerts'

receivers:
- name: 'default'

- name: 'devops-alerts'
  slack_configs:
  - channel: '(( channel ))'
    color: '{{ template "slack.color" . }}'
    title: '{{ template "slack.title" . }}'
    text: '{{ template "slack.text" . }}'
    send_resolved: true
    icon_url: https://avatars3.githubusercontent.com/u/3380462

templates: ['/etc/alertmanager/*.tmpl']