version: '3.7'

networks:
  pgastack:
    driver: bridge

volumes:
  certs: {}
  prometheus_data: {}
  grafana_data: {}


x-op-restart-policy: &restart_policy
  restart: unless-stopped

services:
  traefik:
    hostname: traefik
    image: traefik:latest
    container_name: traefik
    networks:
      - pgastack
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/tls.yml:/etc/traefik/tls.yml:ro
      - certs:/etc/ssl/traefik:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.${DOMAIN:-traefik.me}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth"
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=${TRAEFIK_USER?Variable is not set}:${TRAEFIK_PASSWD?Variable is not set}"
    command:
      - "--api"
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      - "--providers.docker=true"
      - "--providers.docker.watch"
      - "--providers.file.filename=/etc/traefik/tls.yml"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
    <<: *restart_policy
  
  prometheus:
    hostname: prometheus
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - pgastack
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=inbound"
      - "traefik.http.routers.prometheus.service=prometheus"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.${DOMAIN:-traefik.me}`)"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.routers.prometheus.middlewares=prometheus-auth"
      - "traefik.http.middlewares.prometheus-auth.basicauth.users=${TRAEFIK_USER?Variable is not set}:${TRAEFIK_PASSWD?Variable is not set}"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    <<: *restart_policy

  grafana:
    hostname: grafana
    image: grafana/grafana:9.1.1
    container_name: grafana
    networks:
      - pgastack
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD:-grafana}
      - GF_USERS_ALLOW_SIGN_UP=false
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=inbound"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN:-traefik.me}`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.middlewares=grafana-auth"
      - "traefik.http.middlewares.grafana-auth.basicauth.users=${TRAEFIK_USER?Variable is not set}:${TRAEFIK_PASSWD?Variable is not set}"
    <<: *restart_policy

  alertmanager:
    hostname: alertmanager
    image: prom/alertmanager:latest
    container_name: alertmanager
    networks:
      - pgastack
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=inbound"
      - "traefik.http.routers.alertmanager.service=alertmanager"
      - "traefik.http.services.alertmanager.loadbalancer.server.port=9093"
      - "traefik.http.routers.alertmanager.rule=Host(`alertmanager.${DOMAIN:-traefik.me}`)"
      - "traefik.http.routers.alertmanager.entrypoints=websecure"
      - "traefik.http.routers.alertmanager.tls=true"
      - "traefik.http.routers.alertmanager.middlewares=alertmanager-auth"
      - "traefik.http.middlewares.alertmanager-auth.basicauth.users=${TRAEFIK_USER?Variable is not set}:${TRAEFIK_PASSWD?Variable is not set}"
    <<: *restart_policy

  karma:
    hostname: karma
    image: lmierzwa/karma:latest
    networks:
      - pgastack
    environment:
      - "PORT=8989"
      - "ALERTMANAGER_URI=http://alertmanager:9093"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=inbound"
      - "traefik.http.routers.karma.service=karma"
      - "traefik.http.services.karma.loadbalancer.server.port=8989"
      - "traefik.http.routers.karma.rule=Host(`karma.${DOMAIN:-traefik.me}`)"
      - "traefik.http.routers.karma.entrypoints=websecure"
      - "traefik.http.routers.karma.tls=true"
      - "traefik.http.routers.karma.middlewares=karma-auth"
      - "traefik.http.middlewares.karma-auth.basicauth.users=${TRAEFIK_USER?Variable is not set}:${TRAEFIK_PASSWD?Variable is not set}"
    <<: *restart_policy

  certs:
    image: alpine
    volumes:
      - certs:/etc/ssl/traefik
    command: sh -c "cd /etc/ssl/traefik
      && wget traefik.me/cert.pem -O cert.pem
      && wget traefik.me/privkey.pem -O privkey.pem"