version: '3.7'

networks:
  traefik:
    driver: overlay
    name: traefik
    ipam:
      config:
        - subnet: "10.95.1.0/24"
  inbound:
    driver: overlay
    name: inbound
    ipam:
      config:
        - subnet: "10.95.2.0/24"

volumes:
  certs: {}
  prometheus_data: {}
  alertmanager: {}
  grafana_data: {}

services:
  traefik:
    hostname: traefik
    image: traefik:latest
    networks:
      - traefik
      - inbound
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/tls.yml:/etc/traefik/tls.yml:ro
      - certs:/etc/ssl/traefik:ro
    command:
      - "--api"
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      - "--providers.docker=true"
      - "--providers.docker.watch"
      - "--providers.docker.swarmmode=true"
      - "--providers.file.filename=/etc/traefik/tls.yml"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
        - "traefik.http.routers.dashboard.rule=Host(`dashboard.${DOMAIN:-traefik.me}`)"
        - "traefik.http.routers.dashboard.entrypoints=websecure"
        - "traefik.http.routers.dashboard.tls=true"
        - "traefik.http.routers.dashboard.middlewares=dashboard-auth"
        - "traefik.http.middlewares.dashboard-auth.basicauth.users=${TRAEFIK_USER?Variable is not set}:${TRAEFIK_PASSWD?Variable is not set}"

  prometheus:
    hostname: prometheus
    image: prom/prometheus:latest
    networks:
      - inbound
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=730h'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=inbound"
        - "traefik.http.routers.prometheus.service=prometheus"
        - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
        - "traefik.http.routers.prometheus.rule=Host(`prometheus.${DOMAIN:-traefik.me}`)"
        - "traefik.http.routers.prometheus.entrypoints=websecure"
        - "traefik.http.routers.prometheus.tls=true"
        - "traefik.http.routers.prometheus.middlewares=prometheus-auth"
        - "traefik.http.middlewares.prometheus-auth.basicauth.users=${PROM_AUTH_USER?Variable is not set}:${PROM_AUTH_PASSWD?Variable is not set}"

  grafana:
    hostname: grafana
    image: grafana/grafana:9.1.1
    networks:
      - inbound
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD:-grafana}
      - GF_USERS_ALLOW_SIGN_UP=false
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=inbound"
        - "traefik.http.routers.grafana.service=grafana"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
        - "traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN:-traefik.me}`)"
        - "traefik.http.routers.grafana.entrypoints=websecure"
        - "traefik.http.routers.grafana.tls=true"

  alertmanager:
    hostname: alertmanager
    image: prom/alertmanager:latest
    networks:
      - inbound
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./alertmanager:/etc/alertmanager
      - ./alertmanager/alerts.tmpl:/etc/alertmanager/config/alerts.tmpl
      - alertmanager:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=inbound"
        - "traefik.http.routers.alertmanager.service=alertmanager"
        - "traefik.http.services.alertmanager.loadbalancer.server.port=9093"
        - "traefik.http.routers.alertmanager.rule=Host(`alertmanager.${DOMAIN:-traefik.me}`)"
        - "traefik.http.routers.alertmanager.entrypoints=websecure"
        - "traefik.http.routers.alertmanager.tls=true"
        - "traefik.http.routers.alertmanager.middlewares=alertmanager-auth"
        - "traefik.http.middlewares.alertmanager-auth.basicauth.users=${AM_AUTH_USER?Variable is not set}:${AM_AUTH_PASSWD?Variable is not set}"

  karma:
    image: lmierzwa/karma:latest
    networks:
      - inbound
    environment:
      - "PORT=8989"
      - "ALERTMANAGER_URI=http://alertmanager:9093"
    deploy:    
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=inbound"
        - "traefik.http.routers.karma.service=karma"
        - "traefik.http.services.karma.loadbalancer.server.port=8989"
        - "traefik.http.routers.karma.rule=Host(`karma.${DOMAIN:-traefik.me}`)"
        - "traefik.http.routers.karma.entrypoints=websecure"
        - "traefik.http.routers.karma.tls=true"
        - "traefik.http.routers.karma.middlewares=karma-auth"
        - "traefik.http.middlewares.karma-auth.basicauth.users=${KARMA_AUTH_USER?Variable is not set}:${KARMA_AUTH_PASSWD?Variable is not set}"
  
  node-exporter:
    image: prom/node-exporter:latest
    networks:
      - inbound
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    environment:
      - NODE_ID={{.Node.ID}}

    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  certs:
    image: alpine
    volumes:
      - certs:/etc/ssl/traefik
    command: sh -c "cd /etc/ssl/traefik
      && wget traefik.me/cert.pem -O cert.pem
      && wget traefik.me/privkey.pem -O privkey.pem"
    deploy:
      placement:
        constraints: [node.role == manager]